name: "HTML to IPA: Build and Upload (Unsigned)"

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *'
    - cron: '0 0 1 4 *'
    - cron: '0 0 30 6 *'
    - cron: '0 0 28 9 *'
    - cron: '0 0 27 12 *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Install Dependencies
        run: npm install

      - name: Copy Web Files to iOS
        run: npx cap copy ios

      - name: Install CocoaPods Dependencies
        run: |
          cd ios/App
          pod install

      - name: Build iOS App Archive (Target iOS 13+)
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -archivePath output.xcarchive archive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO -destination "generic/platform=iOS"

      - name: Package Unsigned IPA (Rename to pcfire.app and pcfire.ipa)
        run: |
          # Navigate to the directory containing the built .app bundle.
          cd ios/App/output.xcarchive/Products/Applications
          # Rename the .app bundle
          mv App.app pcfire.app
          # Create a Payload folder and move the renamed app into it.
          mkdir Payload
          mv pcfire.app Payload/
          # Zip the Payload folder into an IPA file.
          zip -r pcfire.ipa Payload
          # Move the IPA to a known location for later upload.
          mv pcfire.ipa ../../..

      - name: Set Environment Variables
        run: |
          set -x
          T2=$(TZ=UTC-2 date +'%Y%m%d_%H%M%S')
          TS=$(date -j -f "%Y%m%d_%H%M%S" "${T2}" +%s)
          SHASH=$(git rev-parse --short HEAD)
          echo "ctime=${T2}" >> $GITHUB_ENV
          echo "ctimestamp=${TS}" >> $GITHUB_ENV
          echo "shorthash=${SHASH}" >> $GITHUB_ENV

      - name: Upload IPA
        id: html-to-ipa-upload
        uses: actions/upload-artifact@v4
        with:
          name: pcfire.ipa
          path: ios/App/pcfire.ipa
