name: Build iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Install Capacitor & iOS Platform
        run: |
          npm install -g @capacitor/cli
          npx cap sync ios

      - name: Build iOS App
        run: |
          cd ios/App
          xcodebuild -scheme App -archivePath output.xcarchive archive
          xcodebuild -exportArchive -archivePath output.xcarchive -exportPath output -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: MyApp.ipa
          path: ios/App/output/*.ipa
